# Define the default target
.PHONY: run config

# Define the target to run the main.go file
run:
	@cd vdf-node/cmd && go run main.go

# Define the target to edit the config.json file
config:
	@cd vdf-node && vi config.json
